### ISSUE TITLE
why AP-s is so poor！

### ISSUE THREAD

**Issue by niecongchong** [easton-cau/SOTR#1]
![image](https://user-images.githubusercontent.com/50539160/129861703-d6cb6db3-009b-4582-8d6c-065876f6ef61.png)
I am confused about your results. 
* AP-s is very poor；
* But AP-l far exceeds the current methods;
what is the reason for this?

**Comment by easton-cau** [comment]
Thanks for your attention.

There are several potential reasons. First, the feature maps that we feed to the transformer are divided into a uniform grid of N*N, and a grid cell only predicts an object instance, which may miss some small objects. Also, the transformer can better build long-range dependencies and capture global features, thus leading to excellent performance on larger objects, but it neglects small objects and local information to a certain extent. Furthermore, the relative low-resolution feature maps P5 with positional information are obtained from the transformer module and combined with P2-P4 in FPN to generate final masks, making it harder for the model to segment small objects precisely. We expect that future work will improve this aspect.

I believe I have answered your question, and as such I'm closing the issue, but let us know if you have further questions.
