### ISSUE TITLE
about the latency, seems need 100ms+ on 3090

### ISSUE THREAD

**Issue by lucasjinreal** [easton-cau/SOTR#12]
150ms average, is that normal? I changed everything into GPU.

![image](https://user-images.githubusercontent.com/21303438/139632911-0fd8e22e-9094-4dec-a317-275e376aeb77.png)

using r50 version

**Comment by easton-cau** [comment]
We spend about 140ms per image on 4 Tesla V100. We find that the inference time using multiple GPUs is relatively stable. Moreover, the depth of transformer has a great influence on inference time.
