### ISSUE TITLE
pytorch版本

### ISSUE THREAD

**Issue by roar-1128** [easton-cau/SOTR#8]
只有pytorch1.6版本对应有detectron2==0.2.1.
pytorch>1.7版本对应detectron2==0.5

但是要求pytorch>1.7，detectron2==0.2.1.

请问应该如何解决呢
期待作者的回复

**Comment by easton-cau** [comment]
Our environment：

> torch                   1.7.1
torchvision             0.8.2
detectron2              0.2.1 


Build detectron2 from [https://github.com/facebookresearch/detectron2/releases](url).

**Comment by roar-1128** [comment]
torch1.7.1中没有0.2.1版本的detectron2

**Comment by easton-cau** [comment]
![image](https://user-images.githubusercontent.com/83173745/134687974-f03f3944-bd43-4c66-b217-45f2ec3e638a.png)

1.download detectron2-0.2.1.zip
2.unzip detectron2-0.2.1.zip
3.cd detectron2 && pip install -e .
